spring.application.name: ${{ values.appName }}

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping: DEBUG
